config/routes.rb
CareConnect::Application.routes.draw do
  
  

  devise_for :users

  root to: 'home#home'

  resources :activities
  resources :events
  resources :messages
  resources :comments
  resources :attendances, only: [:create, :destroy]
  resources :users do 
    put 'approve'
    put 'decline'
  end 



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :dob, :house, :location, :school, :role, :about_me, :profile_image

  validates :name, :location, :house, :school, :email, :password, :password_confirmation, presence: true, on: :create
  

  mount_uploader :profile_image, ProfileImageUploader

  has_many :messages_as_sender, class_name: 'Message', foreign_key: :sender_id, dependent: :destroy 
  has_many :messages_as_receiver, class_name: 'Message', foreign_key: :receiver_id, dependent: :destroy 

  has_many :attendances
  has_many :events, through: :attendances
  has_many :comments

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # PUT /users/1/approve
  # PUT /users/1/approve.json
  def approve
    @user = User.find(params[:user_id])
    @user.role = 'approved'
    @user.save

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { render json: @user }
    end
  end

  def pending
    @user = User.find(params[:user_id])
    @user.role = 'pending'
    @user.save

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { render json: @user }
    end
  end

  # PUT /users/1/decline
  # PUT /users/1/decline.json
  def decline
    @user = User.find(params[:user_id])
    @user.role = 'declined'
    @user.save

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { render json: @user }
    end
  end

  # def profile
  #   @user = User.find(params[:user_id])
  # end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.role? :admin %>
    <div class="field">
      <%= f.label :role %><br />
      <%= f.text_field :role %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :house %><br />
    <%= f.text_area :house %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
 <!--  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_area :password %>
  </div> -->
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_area :school %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>

  <div class="field">
    <%= f.label :about_me %><br />
    <%= f.text_area :about_me %>
  </div>

  <div class="field">
      <%= f.label :profile_image %><br />
      <%= f.file_field :profile_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 id="users-table-page">Listing users</h1>

<button id="new-user-button"><%= link_to 'New User', new_user_path %></button>

<div class="usertable">
<table>
  <tr>
    <th>User Type</th>
    <th>Name</th>
    <th>House</th>
    <!-- <th>Email</th> -->
    <!-- <th>School</th> -->
    <th>Location</th>
    <th>Dob</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @users.each do |user| %>
    <% unless user == current_user %>
  <tr>
    <td><%= user.role %></td>
    <td><%= link_to user.name, user %></td>
    <td><%= user.house %></td>
    <!-- <td><%= user.email %></td> -->
    <!-- <td><%= user.school %></td> -->
    <td><%= user.location %></td>
    <td><%= user.dob %></td>
    
        <td>
            <button id="eventbutton">
                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
            </button>
        </td>
        <td>
            <button id="eventbutton">
                <%= (link_to 'Approve', user_approve_path(user), method: :put) unless user == current_user %>
            </button>
        </td>
        <td>
            <button id="eventbutton">
                <%= (link_to 'Decline', user_decline_path(user), method: :put) unless user == current_user %>
            </button>
        </td>
    
  </tr>
  <% end %>
<% end %>
</table>
</div>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 id="profile-page">Profile Page</h1>

<div class="user-image">
  <p>
    <!-- <b>Image</b> -->
  </p>
  <%= link_to image_tag(@user.profile_image.thumb.url), @user.profile_image.detail.url %>
</p>
<!--   <%= image_tag @user.profile_image.url %> -->
</div>
<div class="profile-page">

  <div class="userprofile">  
    <p>
      <b>Name:</b>
    </p>
    <%= @user.name %>
  </div>

  <div class="userprofile">
    <p>
      <b>Dob:</b>
      <%= @user.dob %>
    </p>
  </div>

  <div class="userprofile">
    <p>
      <b>House:</b>
      <%= @user.house %>
    </p>
  </div>

  <div class="userprofile">
    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>
  </div>

  <div class="userprofile">
    <p>
      <b>School:</b>
      <%= @user.school %>
    </p>
  </div>

  <div class="userprofile">
    <p>
      <b>Location:</b>
      <%= @user.location %>
    </p>
  </div>

  <div class="about-me">
    <p>
      <b>About Me:</b>
      <%= @user.about_me %>
    </p>
  </div>
</div>


<div class="profile-buttons">
  <p>
    <button><%= link_to 'Edit', edit_user_path(@user) %> </button>
    <button> <%= link_to 'Back', users_path %> </button>
  </p>
</div>