config/routes.rb
CareConnect::Application.routes.draw do
  
  

  devise_for :users

  root to: 'home#home'

  resources :activities
  resources :events
  resources :messages
  resources :comments
  resources :attendances, only: [:create, :destroy]
  resources :users do 
    put 'approve'
    put 'decline'
  end 



end

app/models/event.rb
class Event < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  attr_accessible :date, :name, :location, :latitude, :longitude, :about_event

  validates :date, :name, :location, :about_event, presence: true, on: :create
  
  validate :date_future
  
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  has_many :comments, :as => :commentable 

  geocoded_by :location
  after_validation :geocode


  private

  def date_future
    errors.add :base, "Date must be in future" if date.past?
  end 

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  # GET /events
  # GET /events.json
  def index

    if params[:search].present?
      @event = Event.near(params[:search], 50, :order => :distance)
    else 
      @events = Event.all

      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @current_year = Date.current.year

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])



    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
    <div class="field">
      <%= f.label :latitude %><br />
      <%= f.text_field :latitude %>
    </div>
    <div class="field">
      <%= f.label :longitude %><br />
      <%= f.text_field :longitude %>
    </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, start_year: @current_year %>
  </div>
  <div class="field">
    <%= f.label :about_event %><br />
    <%= f.text_area :about_event %>
    <%= f.submit %>
  </div>
  <br>
  
<% end %>

app/views/events/edit.html.erb
<div class="editing-event">
<h1>Editing event</h1>

<%= render 'form' %>

<div class="show-buttons">
<button id="edit-show-back"><%= link_to 'Show', @event %></button>
<button id="edit-show-back"><%= link_to 'Back', events_path %></button>
</div>

app/views/events/index.html.erb
<h1 id="heading">Come along to one of our great events!</h1>

<% if can? :update, @event %>
<button id="new-event">   
   <%= link_to 'New Event', new_event_path %>
   <% end %>
</button>

<p>
   <section id="map-canvas"></section>
</p>

<table id="eventtable">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th></th>
    <% if can? :update, @event %> 
    <th></th>
    <th></th>
    <% end %>
  </tr>
  <% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.date %></td>
    <td><%= event.location %></td>
    <td><button id="eventbutton"><%= link_to 'Show', event %></button></td>
    <% if can? :update, @event %>
    <td><button id="eventbutton"><%= link_to 'Edit', edit_event_path(event) %></button></td>
    <td><button id="eventbutton"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
    <% end %>
  </tr>
  <% end %>
</table>
<br />

app/views/events/new.html.erb
<h1 id="newheading">Create new event</h1>

<button id="eventbackbutton"><%= link_to 'Back', events_path %></button>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"></p>

<h1 id="eventname">Event - <%= @event.name %></h1>

<p>
  <button id="attend"><%= link_to 'Attend', attendances_path(event_id: @event.id), method: :post %>
  </button>
</p>
<br>
<div class="showevent">
  <p>
    <b>Event Name</b>
  </p>
  <br>
  <%= @event.name %>
</div>
<div class="showevent">
  <p>
    <b>Date</b>
  </p>
  <br>
  <%= @event.date %>
</div>

<div class="showevent">
  <p>
    <b>Location</b>
  </p>
  <br>
  <%= @event.location %>
</div>

<div class="showevent">
  <p>
    <b>About Event</b>
  </p>
  <br>
  <%= @event.about_event %>
</div>


<div class="map">
  <p>
    <b>Event Map</b>
  </p>
  <br>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}" %>
  
</div>

<div class="people-attending">
  <p>
    <b>People Attending</b>
  </p>
  <br>
  <% @event.attendees.each do |attendee| %>
  <button id="attendee"><%= link_to attendee.name, attendee %></button><br>
  <% end %>

</div>

<div class="nearby-events">
  <p>
    <b>Other Nearby Events</b>
  </p>
  <br>
  <ul>
    <% for event in @event.nearbys(20) %>
    <p><button id="nearby-events"><%= link_to event.location, event %></button> - (<%= event.distance.to_f.round(2) %> miles away) </p><br>
    <% end %>
  </ul>
</div>

<br>
<div class="edit-back">
  <% if can? :update, @event %>
  <button id="event-edit-back"><%= link_to 'Edit', edit_event_path(@event) %></button> 
  <button id="event-edit-back"><%= link_to 'Back', events_path%> </button>
  <% end %>
  <br><br>
</div>

<div class="comments">
  <p>
    <h1>Comments </h1><br>
    <% @event.comments.each do |comment| %>
    <%= render comment %><br>
    <% end %>
  </p>

  <% if can? :create, Comment %>
  <%= form_for Comment.new do |f| %>
  <%= hidden_field_tag :event_id, @event.id %>
  <p> <%= f.label :comment, 'Please add your comments below' %> </p>
  <br>
  
  <%= f.text_area :comment %>
  <br>
  <%= f.submit %>
  <% end %>
  <% end %>
</div>