config/routes.rb
CareConnect::Application.routes.draw do
  
  

  devise_for :users

  root to: 'home#home'

  resources :activities
  resources :events
  resources :messages
  resources :comments
  resources :attendances, only: [:create, :destroy]
  resources :users do 
    put 'approve'
    put 'decline'
  end 



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareConnect</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:400,700,700italic|Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to "Care Connect", root_path %></li>
        <% if current_user %>
        <li>Hello <%= current_user.email %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <% if can? :read, @user %>
        <li><%= link_to "Users", users_path %></li>
        <% end %>
        <li><%= link_to "Activities", activities_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li> 
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  
  <% flash.each do |name, msg| %>
  <p class="<%= name %>"><%= msg %></p>
  <% end %>

  <% if params[:controller] == "home" && params[:action] == "home" %>
  <section class="welcome" id="introduction">
    <h1>Care Connect</h1>
    <h3>Helping Children In Care To Connect</h3>
    <h4>Events | Activities | Meet Ups </h4>

  </section> 


  <% end %>

  <main>
    <%= yield %> 
  </main>
  
  <footer id="footer">
    <nav id="footer-nav">

      &copy; Care Connect

    </nav>
  </footer>

</body>

</html>